// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.0
// LVGL version: 8.3.11
// Project name: ytw3_0

#include "../ui.h"

void ui_configPanel_screen_init(void)
{
    ui_configPanel = lv_obj_create(NULL);
    lv_obj_set_flex_flow(ui_configPanel, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_configPanel, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_set_style_radius(ui_configPanel, 35, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Container3 = lv_obj_create(ui_configPanel);
    lv_obj_remove_style_all(ui_Container3);
    lv_obj_set_width(ui_Container3, 280);
    lv_obj_set_height(ui_Container3, 50);
    lv_obj_set_align(ui_Container3, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Container3, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label17 = lv_label_create(ui_Container3);
    lv_obj_set_width(ui_Label17, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label17, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label17, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label17, "Settings");
    lv_obj_set_style_text_font(ui_Label17, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Container5 = lv_obj_create(ui_configPanel);
    lv_obj_remove_style_all(ui_Container5);
    lv_obj_set_width(ui_Container5, 280);
    lv_obj_set_height(ui_Container5, 50);
    lv_obj_set_x(ui_Container5, 63);
    lv_obj_set_y(ui_Container5, -153);
    lv_obj_set_align(ui_Container5, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Container5, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label30 = lv_label_create(ui_Container5);
    lv_obj_set_width(ui_Label30, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label30, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label30, -65);
    lv_obj_set_y(ui_Label30, 0);
    lv_obj_set_align(ui_Label30, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label30, "FlashLight");
    lv_obj_set_style_text_font(ui_Label30, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Dropdown3 = lv_dropdown_create(ui_Container5);
    lv_dropdown_set_options(ui_Dropdown3, "90\n120\n150\n180\n240\n300");
    lv_obj_set_width(ui_Dropdown3, 100);
    lv_obj_set_height(ui_Dropdown3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Dropdown3, 70);
    lv_obj_set_y(ui_Dropdown3, 0);
    lv_obj_set_align(ui_Dropdown3, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Dropdown3, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_set_style_shadow_color(ui_Dropdown3, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_Dropdown3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_Dropdown3, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_Dropdown3, 1, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_outline_color(lv_dropdown_get_list(ui_Dropdown3), lv_color_hex(0x000000),
                                   LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_opa(lv_dropdown_get_list(ui_Dropdown3), 255,  LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_width(lv_dropdown_get_list(ui_Dropdown3), 1,  LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_pad(lv_dropdown_get_list(ui_Dropdown3), 1,  LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(lv_dropdown_get_list(ui_Dropdown3), lv_color_hex(0x000000),
                                  LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(lv_dropdown_get_list(ui_Dropdown3), 255,  LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(lv_dropdown_get_list(ui_Dropdown3), 1,  LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(lv_dropdown_get_list(ui_Dropdown3), 1,  LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Container1 = lv_obj_create(ui_configPanel);
    lv_obj_remove_style_all(ui_Container1);
    lv_obj_set_width(ui_Container1, 280);
    lv_obj_set_height(ui_Container1, 50);
    lv_obj_set_align(ui_Container1, LV_ALIGN_TOP_MID);
    lv_obj_clear_flag(ui_Container1, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label11 = lv_label_create(ui_Container1);
    lv_obj_set_width(ui_Label11, 130);
    lv_obj_set_height(ui_Label11, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label11, -65);
    lv_obj_set_y(ui_Label11, 0);
    lv_obj_set_align(ui_Label11, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label11, "Screen Off");
    lv_obj_clear_flag(ui_Label11, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                      LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                      LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_text_font(ui_Label11, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Dropdown1 = lv_dropdown_create(ui_Container1);
    lv_dropdown_set_options(ui_Dropdown1, "10s\n15s\n20s\n30s\n1min\n5min\n10min\nnever");
    lv_obj_set_width(ui_Dropdown1, 100);
    lv_obj_set_height(ui_Dropdown1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Dropdown1, 70);
    lv_obj_set_y(ui_Dropdown1, 0);
    lv_obj_set_align(ui_Dropdown1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Dropdown1, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_set_style_outline_color(ui_Dropdown1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_opa(ui_Dropdown1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_width(ui_Dropdown1, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_pad(ui_Dropdown1, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_Dropdown1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_Dropdown1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_outline_color(lv_dropdown_get_list(ui_Dropdown1), lv_color_hex(0x000000),
                                   LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_opa(lv_dropdown_get_list(ui_Dropdown1), 255,  LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_width(lv_dropdown_get_list(ui_Dropdown1), 1,  LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_pad(lv_dropdown_get_list(ui_Dropdown1), 1,  LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Container4 = lv_obj_create(ui_configPanel);
    lv_obj_remove_style_all(ui_Container4);
    lv_obj_set_width(ui_Container4, 280);
    lv_obj_set_height(ui_Container4, 50);
    lv_obj_set_x(ui_Container4, 63);
    lv_obj_set_y(ui_Container4, -153);
    lv_obj_set_align(ui_Container4, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Container4, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label8 = lv_label_create(ui_Container4);
    lv_obj_set_width(ui_Label8, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label8, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label8, -65);
    lv_obj_set_y(ui_Label8, 0);
    lv_obj_set_align(ui_Label8, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label8, "MainPanel");
    lv_obj_set_style_text_font(ui_Label8, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Dropdown2 = lv_dropdown_create(ui_Container4);
    lv_dropdown_set_options(ui_Dropdown2, "number\npointer\nboth");
    lv_obj_set_width(ui_Dropdown2, 100);
    lv_obj_set_height(ui_Dropdown2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Dropdown2, 70);
    lv_obj_set_y(ui_Dropdown2, 0);
    lv_obj_set_align(ui_Dropdown2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Dropdown2, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_set_style_shadow_color(ui_Dropdown2, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_Dropdown2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_Dropdown2, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_Dropdown2, 1, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_outline_color(lv_dropdown_get_list(ui_Dropdown2), lv_color_hex(0x000000),
                                   LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_opa(lv_dropdown_get_list(ui_Dropdown2), 255,  LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_width(lv_dropdown_get_list(ui_Dropdown2), 1,  LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_pad(lv_dropdown_get_list(ui_Dropdown2), 1,  LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(lv_dropdown_get_list(ui_Dropdown2), lv_color_hex(0x000000),
                                  LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(lv_dropdown_get_list(ui_Dropdown2), 255,  LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(lv_dropdown_get_list(ui_Dropdown2), 1,  LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(lv_dropdown_get_list(ui_Dropdown2), 1,  LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Container2 = lv_obj_create(ui_configPanel);
    lv_obj_remove_style_all(ui_Container2);
    lv_obj_set_width(ui_Container2, 280);
    lv_obj_set_height(ui_Container2, 50);
    lv_obj_set_x(ui_Container2, 67);
    lv_obj_set_y(ui_Container2, 70);
    lv_obj_set_align(ui_Container2, LV_ALIGN_TOP_MID);
    lv_obj_clear_flag(ui_Container2, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                      LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                      LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags

    ui_Label7 = lv_label_create(ui_Container2);
    lv_obj_set_width(ui_Label7, 130);
    lv_obj_set_height(ui_Label7, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label7, -65);
    lv_obj_set_y(ui_Label7, 0);
    lv_obj_set_align(ui_Label7, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label7, "About");
    lv_obj_clear_flag(ui_Label7, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                      LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                      LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_text_font(ui_Label7, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_Dropdown3, ui_event_Dropdown3, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Container5, ui_event_Container5, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Dropdown1, ui_event_Dropdown1, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Dropdown2, ui_event_Dropdown2, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Container4, ui_event_Container4, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Container2, ui_event_Container2, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_configPanel, ui_event_configPanel, LV_EVENT_ALL, NULL);

}
