// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.0
// LVGL version: 8.3.11
// Project name: ytw3_0

#include "../ui.h"

void ui_MainPanel_screen_init(void)
{
    ui_MainPanel = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_MainPanel, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_MainPanel, 35, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel3 = lv_obj_create(ui_MainPanel);
    lv_obj_set_width(ui_Panel3, 50);
    lv_obj_set_height(ui_Panel3, 35);
    lv_obj_set_x(ui_Panel3, 95);
    lv_obj_set_y(ui_Panel3, -80);
    lv_obj_set_align(ui_Panel3, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Panel3, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Panel3, lv_color_hex(0x47C00C), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_shiShi = lv_label_create(ui_MainPanel);
    lv_obj_set_width(ui_shiShi, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_shiShi, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_shiShi, -75);
    lv_obj_set_y(ui_shiShi, -20);
    lv_obj_set_align(ui_shiShi, LV_ALIGN_CENTER);
    lv_label_set_text(ui_shiShi, "0");
    lv_obj_clear_flag(ui_shiShi, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                      LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                      LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_scrollbar_mode(ui_shiShi, LV_SCROLLBAR_MODE_OFF);
    lv_obj_set_style_text_color(ui_shiShi, lv_color_hex(0x0A7C0E), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_shiShi, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_shiShi, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_shiShi, &lv_font_montserrat_48, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_shiGe = lv_label_create(ui_MainPanel);
    lv_obj_set_width(ui_shiGe, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_shiGe, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_shiGe, -35);
    lv_obj_set_y(ui_shiGe, -20);
    lv_obj_set_align(ui_shiGe, LV_ALIGN_CENTER);
    lv_label_set_text(ui_shiGe, "0");
    lv_obj_clear_flag(ui_shiGe, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                      LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                      LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_text_color(ui_shiGe, lv_color_hex(0x0A7C0E), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_shiGe, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_shiGe, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_shiGe, &lv_font_montserrat_48, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_fenShi = lv_label_create(ui_MainPanel);
    lv_obj_set_width(ui_fenShi, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_fenShi, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_fenShi, 35);
    lv_obj_set_y(ui_fenShi, -20);
    lv_obj_set_align(ui_fenShi, LV_ALIGN_CENTER);
    lv_label_set_text(ui_fenShi, "0");
    lv_obj_clear_flag(ui_fenShi, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                      LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                      LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_text_color(ui_fenShi, lv_color_hex(0x0A7C0E), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_fenShi, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_fenShi, &lv_font_montserrat_48, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_fenGe = lv_label_create(ui_MainPanel);
    lv_obj_set_width(ui_fenGe, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_fenGe, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_fenGe, 75);
    lv_obj_set_y(ui_fenGe, -20);
    lv_obj_set_align(ui_fenGe, LV_ALIGN_CENTER);
    lv_label_set_text(ui_fenGe, "0");
    lv_obj_clear_flag(ui_fenGe, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                      LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                      LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_text_color(ui_fenGe, lv_color_hex(0x0A7C0E), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_fenGe, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_fenGe, &lv_font_montserrat_48, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label1 = lv_label_create(ui_MainPanel);
    lv_obj_set_width(ui_Label1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label1, 0);
    lv_obj_set_y(ui_Label1, -22);
    lv_obj_set_align(ui_Label1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label1, ":");
    lv_obj_set_style_text_color(ui_Label1, lv_color_hex(0x0A7C0E), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label1, &lv_font_montserrat_48, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_dianliang1 = lv_label_create(ui_MainPanel);
    lv_obj_set_width(ui_dianliang1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_dianliang1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_dianliang1, 95);
    lv_obj_set_y(ui_dianliang1, -80);
    lv_obj_set_align(ui_dianliang1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_dianliang1, "0");
    lv_obj_add_state(ui_dianliang1, LV_STATE_DISABLED);       /// States
    lv_obj_clear_flag(ui_dianliang1, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                      LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                      LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_text_align(ui_dianliang1, LV_TEXT_ALIGN_RIGHT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_dianliang1, &lv_font_montserrat_22, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_miaoShi = lv_label_create(ui_MainPanel);
    lv_obj_set_width(ui_miaoShi, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_miaoShi, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_miaoShi, 60);
    lv_obj_set_y(ui_miaoShi, 20);
    lv_obj_set_align(ui_miaoShi, LV_ALIGN_CENTER);
    lv_label_set_text(ui_miaoShi, "0");
    lv_obj_set_style_text_color(ui_miaoShi, lv_color_hex(0x0A7C0E), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_miaoShi, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_miaoShi, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_miaoGe = lv_label_create(ui_MainPanel);
    lv_obj_set_width(ui_miaoGe, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_miaoGe, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_miaoGe, 80);
    lv_obj_set_y(ui_miaoGe, 20);
    lv_obj_set_align(ui_miaoGe, LV_ALIGN_CENTER);
    lv_label_set_text(ui_miaoGe, "0");
    lv_obj_set_style_text_color(ui_miaoGe, lv_color_hex(0x0A7C0E), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_miaoGe, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_miaoGe, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label4 = lv_label_create(ui_MainPanel);
    lv_obj_set_width(ui_Label4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label4, -50);
    lv_obj_set_y(ui_Label4, 22);
    lv_obj_set_align(ui_Label4, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label4, "2024/1/1");
    lv_obj_set_style_text_color(ui_Label4, lv_color_hex(0x0A7C0E), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label4, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label5 = lv_label_create(ui_MainPanel);
    lv_obj_set_width(ui_Label5, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label5, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label5, 20);
    lv_obj_set_y(ui_Label5, 22);
    lv_obj_set_align(ui_Label5, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label5, "MON");
    lv_obj_set_style_text_color(ui_Label5, lv_color_hex(0x0A7C0E), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label5, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label2 = lv_label_create(ui_MainPanel);
    lv_obj_set_width(ui_Label2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label2, 0);
    lv_obj_set_y(ui_Label2, 60);
    lv_obj_set_align(ui_Label2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label2, "Weather");
    lv_obj_set_style_text_color(ui_Label2, lv_color_hex(0x0A7C0E), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label2, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_MainPanel, ui_event_MainPanel, LV_EVENT_ALL, NULL);

}
