// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.0
// LVGL version: 8.3.11
// Project name: ytw3_0

#include "../ui.h"

void ui_MainPanel2_screen_init(void)
{
    ui_MainPanel2 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_MainPanel2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_MainPanel2, 35, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel4 = lv_obj_create(ui_MainPanel2);
    lv_obj_set_width(ui_Panel4, 50);
    lv_obj_set_height(ui_Panel4, 35);
    lv_obj_set_x(ui_Panel4, 0);
    lv_obj_set_y(ui_Panel4, 50);
    lv_obj_set_align(ui_Panel4, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Panel4, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Panel4, lv_color_hex(0x47C00C), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_dianliang2 = lv_label_create(ui_MainPanel2);
    lv_obj_set_width(ui_dianliang2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_dianliang2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_dianliang2, 0);
    lv_obj_set_y(ui_dianliang2, 50);
    lv_obj_set_align(ui_dianliang2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_dianliang2, "0");
    lv_obj_add_state(ui_dianliang2, LV_STATE_DISABLED);       /// States
    lv_obj_clear_flag(ui_dianliang2, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                      LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                      LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_text_align(ui_dianliang2, LV_TEXT_ALIGN_RIGHT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_dianliang2, &lv_font_montserrat_22, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label19 = lv_label_create(ui_MainPanel2);
    lv_obj_set_width(ui_Label19, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label19, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label19, 0);
    lv_obj_set_y(ui_Label19, 103);
    lv_obj_set_align(ui_Label19, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label19, "12");
    lv_obj_clear_flag(ui_Label19, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                      LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                      LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_text_color(ui_Label19, lv_color_hex(0x7EEAC3), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label19, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label21 = lv_label_create(ui_MainPanel2);
    lv_obj_set_width(ui_Label21, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label21, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label21, 0);
    lv_obj_set_y(ui_Label21, -103);
    lv_obj_set_align(ui_Label21, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label21, "24");
    lv_obj_clear_flag(ui_Label21, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                      LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                      LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_text_color(ui_Label21, lv_color_hex(0x7EEAC3), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label21, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label20 = lv_label_create(ui_MainPanel2);
    lv_obj_set_width(ui_Label20, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label20, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label20, 120);
    lv_obj_set_y(ui_Label20, 0);
    lv_obj_set_align(ui_Label20, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label20, "6");
    lv_obj_clear_flag(ui_Label20, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                      LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                      LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_text_color(ui_Label20, lv_color_hex(0x7EEAC3), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label20, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label22 = lv_label_create(ui_MainPanel2);
    lv_obj_set_width(ui_Label22, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label22, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label22, -120);
    lv_obj_set_y(ui_Label22, 0);
    lv_obj_set_align(ui_Label22, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label22, "18");
    lv_obj_clear_flag(ui_Label22, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                      LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                      LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_text_color(ui_Label22, lv_color_hex(0x7EEAC3), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label22, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Image10 = lv_img_create(ui_MainPanel2);
    lv_img_set_src(ui_Image10, &ui_img_rectangle_8_png);
    lv_obj_set_width(ui_Image10, LV_SIZE_CONTENT);   /// 12
    lv_obj_set_height(ui_Image10, LV_SIZE_CONTENT);    /// 12
    lv_obj_set_x(ui_Image10, -100);
    lv_obj_set_y(ui_Image10, -100);
    lv_obj_set_align(ui_Image10, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Image10, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                      LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                      LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags

    ui_Image8 = lv_img_create(ui_MainPanel2);
    lv_img_set_src(ui_Image8, &ui_img_rectangle_8_png);
    lv_obj_set_width(ui_Image8, LV_SIZE_CONTENT);   /// 12
    lv_obj_set_height(ui_Image8, LV_SIZE_CONTENT);    /// 12
    lv_obj_set_x(ui_Image8, 100);
    lv_obj_set_y(ui_Image8, 100);
    lv_obj_set_align(ui_Image8, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Image8, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                      LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                      LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags

    ui_Image11 = lv_img_create(ui_MainPanel2);
    lv_img_set_src(ui_Image11, &ui_img_rectangle_7_png);
    lv_obj_set_width(ui_Image11, LV_SIZE_CONTENT);   /// 12
    lv_obj_set_height(ui_Image11, LV_SIZE_CONTENT);    /// 12
    lv_obj_set_x(ui_Image11, 100);
    lv_obj_set_y(ui_Image11, -100);
    lv_obj_set_align(ui_Image11, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Image11, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                      LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                      LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags

    ui_Image12 = lv_img_create(ui_MainPanel2);
    lv_img_set_src(ui_Image12, &ui_img_rectangle_7_png);
    lv_obj_set_width(ui_Image12, LV_SIZE_CONTENT);   /// 12
    lv_obj_set_height(ui_Image12, LV_SIZE_CONTENT);    /// 12
    lv_obj_set_x(ui_Image12, -100);
    lv_obj_set_y(ui_Image12, 100);
    lv_obj_set_align(ui_Image12, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Image12, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                      LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                      LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags

    ui_Label23 = lv_label_create(ui_MainPanel2);
    lv_obj_set_width(ui_Label23, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label23, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label23, -90);
    lv_obj_set_y(ui_Label23, -90);
    lv_obj_set_align(ui_Label23, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label23, "21");
    lv_obj_clear_flag(ui_Label23, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                      LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                      LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_text_color(ui_Label23, lv_color_hex(0x7EEAC3), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label23, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label24 = lv_label_create(ui_MainPanel2);
    lv_obj_set_width(ui_Label24, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label24, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label24, 90);
    lv_obj_set_y(ui_Label24, -90);
    lv_obj_set_align(ui_Label24, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label24, "3");
    lv_obj_clear_flag(ui_Label24, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                      LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                      LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_text_color(ui_Label24, lv_color_hex(0x7EEAC3), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label24, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label25 = lv_label_create(ui_MainPanel2);
    lv_obj_set_width(ui_Label25, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label25, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label25, 90);
    lv_obj_set_y(ui_Label25, 90);
    lv_obj_set_align(ui_Label25, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label25, "9");
    lv_obj_clear_flag(ui_Label25, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                      LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                      LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_text_color(ui_Label25, lv_color_hex(0x7EEAC3), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label25, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label26 = lv_label_create(ui_MainPanel2);
    lv_obj_set_width(ui_Label26, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label26, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label26, -90);
    lv_obj_set_y(ui_Label26, 90);
    lv_obj_set_align(ui_Label26, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label26, "15");
    lv_obj_clear_flag(ui_Label26, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                      LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                      LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_text_color(ui_Label26, lv_color_hex(0x7EEAC3), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label26, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Image13 = lv_img_create(ui_MainPanel2);
    lv_img_set_src(ui_Image13, &ui_img_rectangle_9_png);
    lv_obj_set_width(ui_Image13, LV_SIZE_CONTENT);   /// 12
    lv_obj_set_height(ui_Image13, LV_SIZE_CONTENT);    /// 11
    lv_obj_set_x(ui_Image13, 121);
    lv_obj_set_y(ui_Image13, -70);
    lv_obj_set_align(ui_Image13, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Image13, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                      LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                      LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags

    ui_Image14 = lv_img_create(ui_MainPanel2);
    lv_img_set_src(ui_Image14, &ui_img_rectangle_10_png);
    lv_obj_set_width(ui_Image14, LV_SIZE_CONTENT);   /// 12
    lv_obj_set_height(ui_Image14, LV_SIZE_CONTENT);    /// 9
    lv_obj_set_x(ui_Image14, 134);
    lv_obj_set_y(ui_Image14, -36);
    lv_obj_set_align(ui_Image14, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Image14, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                      LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                      LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags

    ui_Image15 = lv_img_create(ui_MainPanel2);
    lv_img_set_src(ui_Image15, &ui_img_rectangle_12_png);
    lv_obj_set_width(ui_Image15, LV_SIZE_CONTENT);   /// 9
    lv_obj_set_height(ui_Image15, LV_SIZE_CONTENT);    /// 12
    lv_obj_set_x(ui_Image15, 31);
    lv_obj_set_y(ui_Image15, -115);
    lv_obj_set_align(ui_Image15, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Image15, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                      LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                      LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags

    ui_Image16 = lv_img_create(ui_MainPanel2);
    lv_img_set_src(ui_Image16, &ui_img_rectangle_11_png);
    lv_obj_set_width(ui_Image16, LV_SIZE_CONTENT);   /// 11
    lv_obj_set_height(ui_Image16, LV_SIZE_CONTENT);    /// 12
    lv_obj_set_x(ui_Image16, 64);
    lv_obj_set_y(ui_Image16, -111);
    lv_obj_set_align(ui_Image16, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Image16, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                      LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                      LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags

    ui_Image17 = lv_img_create(ui_MainPanel2);
    lv_img_set_src(ui_Image17, &ui_img_rectangle_9_png);
    lv_obj_set_width(ui_Image17, LV_SIZE_CONTENT);   /// 12
    lv_obj_set_height(ui_Image17, LV_SIZE_CONTENT);    /// 11
    lv_obj_set_x(ui_Image17, -121);
    lv_obj_set_y(ui_Image17, 70);
    lv_obj_set_align(ui_Image17, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Image17, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                      LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                      LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags

    ui_Image18 = lv_img_create(ui_MainPanel2);
    lv_img_set_src(ui_Image18, &ui_img_rectangle_10_png);
    lv_obj_set_width(ui_Image18, LV_SIZE_CONTENT);   /// 12
    lv_obj_set_height(ui_Image18, LV_SIZE_CONTENT);    /// 9
    lv_obj_set_x(ui_Image18, -134);
    lv_obj_set_y(ui_Image18, 36);
    lv_obj_set_align(ui_Image18, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Image18, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                      LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                      LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags

    ui_Image19 = lv_img_create(ui_MainPanel2);
    lv_img_set_src(ui_Image19, &ui_img_rectangle_11_png);
    lv_obj_set_width(ui_Image19, LV_SIZE_CONTENT);   /// 11
    lv_obj_set_height(ui_Image19, LV_SIZE_CONTENT);    /// 12
    lv_obj_set_x(ui_Image19, -64);
    lv_obj_set_y(ui_Image19, 111);
    lv_obj_set_align(ui_Image19, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Image19, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                      LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                      LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags

    ui_Image20 = lv_img_create(ui_MainPanel2);
    lv_img_set_src(ui_Image20, &ui_img_rectangle_12_png);
    lv_obj_set_width(ui_Image20, LV_SIZE_CONTENT);   /// 9
    lv_obj_set_height(ui_Image20, LV_SIZE_CONTENT);    /// 12
    lv_obj_set_x(ui_Image20, -31);
    lv_obj_set_y(ui_Image20, 115);
    lv_obj_set_align(ui_Image20, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Image20, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                      LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                      LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags

    ui_Image21 = lv_img_create(ui_MainPanel2);
    lv_img_set_src(ui_Image21, &ui_img_rectangle_13_png);
    lv_obj_set_width(ui_Image21, LV_SIZE_CONTENT);   /// 9
    lv_obj_set_height(ui_Image21, LV_SIZE_CONTENT);    /// 12
    lv_obj_set_x(ui_Image21, -31);
    lv_obj_set_y(ui_Image21, -115);
    lv_obj_set_align(ui_Image21, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Image21, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                      LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                      LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags

    ui_Image22 = lv_img_create(ui_MainPanel2);
    lv_img_set_src(ui_Image22, &ui_img_rectangle_14_png);
    lv_obj_set_width(ui_Image22, LV_SIZE_CONTENT);   /// 11
    lv_obj_set_height(ui_Image22, LV_SIZE_CONTENT);    /// 12
    lv_obj_set_x(ui_Image22, -64);
    lv_obj_set_y(ui_Image22, -111);
    lv_obj_set_align(ui_Image22, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Image22, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                      LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                      LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags

    ui_Image23 = lv_img_create(ui_MainPanel2);
    lv_img_set_src(ui_Image23, &ui_img_rectangle_15_png);
    lv_obj_set_width(ui_Image23, LV_SIZE_CONTENT);   /// 12
    lv_obj_set_height(ui_Image23, LV_SIZE_CONTENT);    /// 11
    lv_obj_set_x(ui_Image23, -121);
    lv_obj_set_y(ui_Image23, -70);
    lv_obj_set_align(ui_Image23, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Image23, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                      LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                      LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags

    ui_Image24 = lv_img_create(ui_MainPanel2);
    lv_img_set_src(ui_Image24, &ui_img_rectangle_16_png);
    lv_obj_set_width(ui_Image24, LV_SIZE_CONTENT);   /// 12
    lv_obj_set_height(ui_Image24, LV_SIZE_CONTENT);    /// 9
    lv_obj_set_x(ui_Image24, -134);
    lv_obj_set_y(ui_Image24, -36);
    lv_obj_set_align(ui_Image24, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Image24, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                      LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                      LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags

    ui_Image25 = lv_img_create(ui_MainPanel2);
    lv_img_set_src(ui_Image25, &ui_img_rectangle_13_png);
    lv_obj_set_width(ui_Image25, LV_SIZE_CONTENT);   /// 9
    lv_obj_set_height(ui_Image25, LV_SIZE_CONTENT);    /// 12
    lv_obj_set_x(ui_Image25, 32);
    lv_obj_set_y(ui_Image25, 115);
    lv_obj_set_align(ui_Image25, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Image25, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                      LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                      LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags

    ui_Image26 = lv_img_create(ui_MainPanel2);
    lv_img_set_src(ui_Image26, &ui_img_rectangle_14_png);
    lv_obj_set_width(ui_Image26, LV_SIZE_CONTENT);   /// 11
    lv_obj_set_height(ui_Image26, LV_SIZE_CONTENT);    /// 12
    lv_obj_set_x(ui_Image26, 68);
    lv_obj_set_y(ui_Image26, 111);
    lv_obj_set_align(ui_Image26, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Image26, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                      LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                      LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags

    ui_Image27 = lv_img_create(ui_MainPanel2);
    lv_img_set_src(ui_Image27, &ui_img_rectangle_16_png);
    lv_obj_set_width(ui_Image27, LV_SIZE_CONTENT);   /// 12
    lv_obj_set_height(ui_Image27, LV_SIZE_CONTENT);    /// 9
    lv_obj_set_x(ui_Image27, 134);
    lv_obj_set_y(ui_Image27, 36);
    lv_obj_set_align(ui_Image27, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Image27, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                      LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                      LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags

    ui_Image28 = lv_img_create(ui_MainPanel2);
    lv_img_set_src(ui_Image28, &ui_img_rectangle_15_png);
    lv_obj_set_width(ui_Image28, LV_SIZE_CONTENT);   /// 12
    lv_obj_set_height(ui_Image28, LV_SIZE_CONTENT);    /// 11
    lv_obj_set_x(ui_Image28, 121);
    lv_obj_set_y(ui_Image28, 70);
    lv_obj_set_align(ui_Image28, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Image28, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                      LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                      LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags

    ui_Label35 = lv_label_create(ui_MainPanel2);
    lv_obj_set_width(ui_Label35, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label35, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label35, 135);
    lv_obj_set_y(ui_Label35, 0);
    lv_obj_set_align(ui_Label35, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label35, "");
    lv_obj_clear_flag(ui_Label35, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                      LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                      LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_text_color(ui_Label35, lv_color_hex(0x90C7F3), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label35, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label35, &ui_font_changfangxing, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label36 = lv_label_create(ui_MainPanel2);
    lv_obj_set_width(ui_Label36, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label36, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label36, 0);
    lv_obj_set_y(ui_Label36, 115);
    lv_obj_set_align(ui_Label36, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label36, "");
    lv_obj_clear_flag(ui_Label36, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                      LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                      LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_text_color(ui_Label36, lv_color_hex(0x90C7F3), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label36, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label36, &ui_font_changfangxing, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label37 = lv_label_create(ui_MainPanel2);
    lv_obj_set_width(ui_Label37, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label37, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label37, -135);
    lv_obj_set_y(ui_Label37, 0);
    lv_obj_set_align(ui_Label37, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label37, "");
    lv_obj_clear_flag(ui_Label37, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                      LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                      LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_text_color(ui_Label37, lv_color_hex(0x90C7F3), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label37, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label37, &ui_font_changfangxing, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label38 = lv_label_create(ui_MainPanel2);
    lv_obj_set_width(ui_Label38, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label38, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label38, 0);
    lv_obj_set_y(ui_Label38, -115);
    lv_obj_set_align(ui_Label38, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label38, "");
    lv_obj_clear_flag(ui_Label38, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                      LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                      LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_text_color(ui_Label38, lv_color_hex(0x90C7F3), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label38, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label38, &ui_font_changfangxing, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_shiZhen = lv_img_create(ui_MainPanel2);
    lv_img_set_src(ui_shiZhen, &ui_img_rectangle_2_png);
    lv_obj_set_width(ui_shiZhen, LV_SIZE_CONTENT);   /// 60
    lv_obj_set_height(ui_shiZhen, LV_SIZE_CONTENT);    /// 8
    lv_obj_set_x(ui_shiZhen, 0);
    lv_obj_set_y(ui_shiZhen, -26);
    lv_obj_set_align(ui_shiZhen, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_shiZhen, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_shiZhen, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_pivot(ui_shiZhen, 4, 56);

    ui_fenZhen = lv_img_create(ui_MainPanel2);
    lv_img_set_src(ui_fenZhen, &ui_img_rectangle_1_png);
    lv_obj_set_width(ui_fenZhen, LV_SIZE_CONTENT);   /// 8
    lv_obj_set_height(ui_fenZhen, LV_SIZE_CONTENT);    /// 110
    lv_obj_set_x(ui_fenZhen, 0);
    lv_obj_set_y(ui_fenZhen, -51);
    lv_obj_set_align(ui_fenZhen, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_fenZhen, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_fenZhen, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_pivot(ui_fenZhen, 4, 106);

    ui_miaoZhen = lv_img_create(ui_MainPanel2);
    lv_img_set_src(ui_miaoZhen, &ui_img_rectangle_3_png);
    lv_obj_set_width(ui_miaoZhen, LV_SIZE_CONTENT);   /// 4
    lv_obj_set_height(ui_miaoZhen, LV_SIZE_CONTENT);    /// 110
    lv_obj_set_x(ui_miaoZhen, 0);
    lv_obj_set_y(ui_miaoZhen, -53);
    lv_obj_set_align(ui_miaoZhen, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_miaoZhen, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_miaoZhen, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_pivot(ui_miaoZhen, 2, 108);

    ui_Image1 = lv_img_create(ui_MainPanel2);
    lv_img_set_src(ui_Image1, &ui_img_ellipse_1_png);
    lv_obj_set_width(ui_Image1, 12);
    lv_obj_set_height(ui_Image1, 12);
    lv_obj_set_align(ui_Image1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image1, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label43 = lv_label_create(ui_MainPanel2);
    lv_obj_set_width(ui_Label43, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label43, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label43, -63);
    lv_obj_set_y(ui_Label43, -43);
    lv_obj_set_align(ui_Label43, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label43, "Weather");
    lv_obj_set_style_text_color(ui_Label43, lv_color_hex(0x0A7C0E), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label43, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label43, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label27 = lv_label_create(ui_MainPanel2);
    lv_obj_set_width(ui_Label27, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label27, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label27, 93);
    lv_obj_set_y(ui_Label27, 0);
    lv_obj_set_align(ui_Label27, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label27, "MON");
    lv_obj_set_style_text_color(ui_Label27, lv_color_hex(0xEE5A5A), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label27, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label18 = lv_label_create(ui_MainPanel2);
    lv_obj_set_width(ui_Label18, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label18, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label18, 0);
    lv_obj_set_y(ui_Label18, 86);
    lv_obj_set_align(ui_Label18, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label18, "2024/1/1");
    lv_obj_set_style_text_color(ui_Label18, lv_color_hex(0xEE5A5A), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label18, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label18, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_MainPanel2, ui_event_MainPanel2, LV_EVENT_ALL, NULL);

}
