// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.0
// LVGL version: 8.3.11
// Project name: ytw3_0

#include "../ui.h"

void ui_remainsPanel_screen_init(void)
{
    ui_remainsPanel = lv_obj_create(NULL);
    lv_obj_add_flag(ui_remainsPanel, LV_OBJ_FLAG_SCROLL_WITH_ARROW);     /// Flags
    lv_obj_set_flex_flow(ui_remainsPanel, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_remainsPanel, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_set_style_radius(ui_remainsPanel, 35, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Container16 = lv_obj_create(ui_remainsPanel);
    lv_obj_remove_style_all(ui_Container16);
    lv_obj_set_width(ui_Container16, 280);
    lv_obj_set_height(ui_Container16, 70);
    lv_obj_set_align(ui_Container16, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Container16, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_Container16, LV_FLEX_ALIGN_SPACE_AROUND, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_SPACE_AROUND);
    lv_obj_clear_flag(ui_Container16, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label42 = lv_label_create(ui_Container16);
    lv_obj_set_width(ui_Label42, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label42, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label42, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label42, "Remains");
    lv_obj_set_style_text_font(ui_Label42, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Button13 = lv_btn_create(ui_Container16);
    lv_obj_set_width(ui_Button13, 50);
    lv_obj_set_height(ui_Button13, 50);
    lv_obj_set_x(ui_Button13, 99);
    lv_obj_set_y(ui_Button13, -80);
    lv_obj_set_align(ui_Button13, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Button13, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_Button13, LV_FLEX_ALIGN_SPACE_AROUND, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_SPACE_AROUND);
    lv_obj_clear_flag(ui_Button13, LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE |
                      LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                      LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_scrollbar_mode(ui_Button13, LV_SCROLLBAR_MODE_OFF);
    lv_obj_set_scroll_dir(ui_Button13, LV_DIR_TOP);
    lv_obj_set_style_radius(ui_Button13, 20, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Button13, lv_color_hex(0x11BDDC), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Button13, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_Button13, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_Button13, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_Button13, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_Button13, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_ofs_x(ui_Button13, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_ofs_y(ui_Button13, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_Button13, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Button13, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label28 = lv_label_create(ui_Button13);
    lv_obj_set_width(ui_Label28, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label28, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label28, 206);
    lv_obj_set_y(ui_Label28, -47);
    lv_obj_set_align(ui_Label28, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label28, "");
    lv_obj_set_style_text_color(ui_Label28, lv_color_hex(0x8D9E87), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label28, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label28, &ui_font_jiahao48, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_Button13, ui_event_Button13, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_remainsPanel, ui_event_remainsPanel, LV_EVENT_ALL, NULL);

}
