// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.0
// LVGL version: 8.3.11
// Project name: ytw3_0

#include "ui.h"
#include "ui_helpers.h"

///////////////////// VARIABLES ////////////////////


// SCREEN: ui_MainPanel
void ui_MainPanel_screen_init(void);
void ui_event_MainPanel(lv_event_t * e);
lv_obj_t * ui_MainPanel;
lv_obj_t * ui_Panel3;
lv_obj_t * ui_shiShi;
lv_obj_t * ui_shiGe;
lv_obj_t * ui_fenShi;
lv_obj_t * ui_fenGe;
lv_obj_t * ui_Label1;
lv_obj_t * ui_dianliang1;
lv_obj_t * ui_miaoShi;
lv_obj_t * ui_miaoGe;
lv_obj_t * ui_Label4;
lv_obj_t * ui_Label5;
lv_obj_t * ui_Label2;


// SCREEN: ui_MainPanel2
void ui_MainPanel2_screen_init(void);
void ui_event_MainPanel2(lv_event_t * e);
lv_obj_t * ui_MainPanel2;
lv_obj_t * ui_Panel4;
lv_obj_t * ui_dianliang2;
lv_obj_t * ui_Label19;
lv_obj_t * ui_Label21;
lv_obj_t * ui_Label20;
lv_obj_t * ui_Label22;
lv_obj_t * ui_Image10;
lv_obj_t * ui_Image8;
lv_obj_t * ui_Image11;
lv_obj_t * ui_Image12;
lv_obj_t * ui_Label23;
lv_obj_t * ui_Label24;
lv_obj_t * ui_Label25;
lv_obj_t * ui_Label26;
lv_obj_t * ui_Image13;
lv_obj_t * ui_Image14;
lv_obj_t * ui_Image15;
lv_obj_t * ui_Image16;
lv_obj_t * ui_Image17;
lv_obj_t * ui_Image18;
lv_obj_t * ui_Image19;
lv_obj_t * ui_Image20;
lv_obj_t * ui_Image21;
lv_obj_t * ui_Image22;
lv_obj_t * ui_Image23;
lv_obj_t * ui_Image24;
lv_obj_t * ui_Image25;
lv_obj_t * ui_Image26;
lv_obj_t * ui_Image27;
lv_obj_t * ui_Image28;
lv_obj_t * ui_Label35;
lv_obj_t * ui_Label36;
lv_obj_t * ui_Label37;
lv_obj_t * ui_Label38;
lv_obj_t * ui_shiZhen;
lv_obj_t * ui_fenZhen;
lv_obj_t * ui_miaoZhen;
lv_obj_t * ui_Image1;
lv_obj_t * ui_Label43;
lv_obj_t * ui_Label27;
lv_obj_t * ui_Label18;


// SCREEN: ui_ControlPanel
void ui_ControlPanel_screen_init(void);
void ui_event_ControlPanel(lv_event_t * e);
lv_obj_t * ui_ControlPanel;
lv_obj_t * ui_Container14;
lv_obj_t * ui_Label41;
lv_obj_t * ui_Container13;
void ui_event_Button1(lv_event_t * e);
lv_obj_t * ui_Button1;
lv_obj_t * ui_Label3;
void ui_event_Button2(lv_event_t * e);
lv_obj_t * ui_Button2;
lv_obj_t * ui_Label6;
void ui_event_Button3(lv_event_t * e);
lv_obj_t * ui_Button3;
lv_obj_t * ui_Label9;
void ui_event_Button4(lv_event_t * e);
lv_obj_t * ui_Button4;
lv_obj_t * ui_Label40;
lv_obj_t * ui_Button7;
lv_obj_t * ui_Button8;
lv_obj_t * ui_Button9;
lv_obj_t * ui_Button10;
lv_obj_t * ui_Container15;
void ui_event_Slider1(lv_event_t * e);
lv_obj_t * ui_Slider1;


// SCREEN: ui_lightPanel
void ui_lightPanel_screen_init(void);
void ui_event_lightPanel(lv_event_t * e);
lv_obj_t * ui_lightPanel;
lv_obj_t * ui_Panel1;
lv_obj_t * ui_Label10;
lv_obj_t * ui_Label16;


// SCREEN: ui_configPanel
void ui_configPanel_screen_init(void);
void ui_event_configPanel(lv_event_t * e);
lv_obj_t * ui_configPanel;
lv_obj_t * ui_Container3;
lv_obj_t * ui_Label17;
void ui_event_Container5(lv_event_t * e);
lv_obj_t * ui_Container5;
lv_obj_t * ui_Label30;
void ui_event_Dropdown3(lv_event_t * e);
lv_obj_t * ui_Dropdown3;
lv_obj_t * ui_Container1;
lv_obj_t * ui_Label11;
void ui_event_Dropdown1(lv_event_t * e);
lv_obj_t * ui_Dropdown1;
void ui_event_Container4(lv_event_t * e);
lv_obj_t * ui_Container4;
lv_obj_t * ui_Label8;
void ui_event_Dropdown2(lv_event_t * e);
lv_obj_t * ui_Dropdown2;
void ui_event_Container2(lv_event_t * e);
lv_obj_t * ui_Container2;
lv_obj_t * ui_Label7;


// SCREEN: ui_SystemAboutPanel
void ui_SystemAboutPanel_screen_init(void);
void ui_event_SystemAboutPanel(lv_event_t * e);
lv_obj_t * ui_SystemAboutPanel;
lv_obj_t * ui_Label12;


// SCREEN: ui_ShutDown
void ui_ShutDown_screen_init(void);
void ui_event_ShutDown(lv_event_t * e);
lv_obj_t * ui_ShutDown;
lv_obj_t * ui_Label13;
void ui_event_Button5(lv_event_t * e);
lv_obj_t * ui_Button5;
void ui_event_Button6(lv_event_t * e);
lv_obj_t * ui_Button6;
lv_obj_t * ui_Label14;
lv_obj_t * ui_Label15;


// SCREEN: ui_noticePanel
void ui_noticePanel_screen_init(void);
void ui_event_noticePanel(lv_event_t * e);
lv_obj_t * ui_noticePanel;
lv_obj_t * ui_Container6;
lv_obj_t * ui_Label29;


// SCREEN: ui_addRemainsPanel
void ui_addRemainsPanel_screen_init(void);
void ui_event_addRemainsPanel(lv_event_t * e);
lv_obj_t * ui_addRemainsPanel;
lv_obj_t * ui_Container8;
lv_obj_t * ui_TextArea1;
void ui_event_Button11(lv_event_t * e);
lv_obj_t * ui_Button11;
lv_obj_t * ui_Label32;
lv_obj_t * ui_Keyboard1;


// SCREEN: ui_remainsPanel
void ui_remainsPanel_screen_init(void);
void ui_event_remainsPanel(lv_event_t * e);
lv_obj_t * ui_remainsPanel;
lv_obj_t * ui_Container16;
lv_obj_t * ui_Label42;
void ui_event_Button13(lv_event_t * e);
lv_obj_t * ui_Button13;
lv_obj_t * ui_Label28;
lv_obj_t * ui____initial_actions0;
const lv_img_dsc_t * ui_imgset_ellipse_[1] = {&ui_img_ellipse_1_png};
const lv_img_dsc_t * ui_imgset_rectangle_[15] = {&ui_img_rectangle_1_png, &ui_img_rectangle_10_png, &ui_img_rectangle_11_png, &ui_img_rectangle_12_png, &ui_img_rectangle_2_png, &ui_img_rectangle_13_png, &ui_img_rectangle_3_png, &ui_img_rectangle_14_png, &ui_img_rectangle_15_png, &ui_img_rectangle_5_png, &ui_img_rectangle_16_png, &ui_img_rectangle_6_png, &ui_img_rectangle_7_png, &ui_img_rectangle_8_png, &ui_img_rectangle_9_png};


// SCREEN: ui_calenderPanel
void ui_calendarPanel_screen_init(void);
lv_obj_t * ui_calendarPanel;
lv_obj_t * ui_calendar;
lv_obj_t * ui_calendar_header;
void ui_event_calendarPanel(lv_event_t * e);
void ui_event_calendar(lv_event_t * e);


// SCREEN: ui_SchedulePanel
void ui_SchedulePanel_screen_init(void);
lv_obj_t * ui_SchedulePanel;
lv_obj_t * ui_Schedule_label;
void ui_event_SchedulePanel(lv_event_t * e);

///////////////////// TEST LVGL SETTINGS ////////////////////
#if LV_COLOR_DEPTH != 16
#error "LV_COLOR_DEPTH should be 16bit to match SquareLine Studio's settings"
#endif
#if LV_COLOR_16_SWAP !=0
#error "LV_COLOR_16_SWAP should be 0 to match SquareLine Studio's settings"
#endif

///////////////////// ANIMATIONS ////////////////////

///////////////////// FUNCTIONS ////////////////////
void ui_event_MainPanel(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_BOTTOM) {
        lv_indev_wait_release(lv_indev_get_act());
        _ui_screen_change(&ui_ControlPanel, LV_SCR_LOAD_ANIM_OVER_BOTTOM, 300, 0, &ui_ControlPanel_screen_init);
        leaveMainPanel1(e);
    }
    if(event_code == LV_EVENT_SCREEN_LOADED) {
        init_time_counter(e);
    }
    if(event_code == LV_EVENT_CLICKED) {
        changeMainPanel(e);
    }
    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_TOP) {
        lv_indev_wait_release(lv_indev_get_act());
        _ui_screen_change(&ui_noticePanel, LV_SCR_LOAD_ANIM_OVER_TOP, 300, 0, &ui_noticePanel_screen_init);
    }
    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_RIGHT) {
        lv_indev_wait_release(lv_indev_get_act());
        _ui_screen_change(&ui_remainsPanel, LV_SCR_LOAD_ANIM_OVER_RIGHT, 300, 0, &ui_remainsPanel_screen_init);
    }
}
void ui_event_MainPanel2(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        changeMainPanel(e);
    }
    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_BOTTOM) {
        lv_indev_wait_release(lv_indev_get_act());
        _ui_screen_change(&ui_ControlPanel, LV_SCR_LOAD_ANIM_OVER_BOTTOM, 300, 0, &ui_ControlPanel_screen_init);
        leaveMainPanel2(e);
    }
    if(event_code == LV_EVENT_SCREEN_LOADED) {
        init_time_counter_2(e);
    }
    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_TOP) {
        lv_indev_wait_release(lv_indev_get_act());
        _ui_screen_change(&ui_noticePanel, LV_SCR_LOAD_ANIM_OVER_TOP, 300, 0, &ui_noticePanel_screen_init);
    }
    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_RIGHT) {
        lv_indev_wait_release(lv_indev_get_act());
        _ui_screen_change(&ui_remainsPanel, LV_SCR_LOAD_ANIM_OVER_RIGHT, 300, 0, &ui_remainsPanel_screen_init);
    }
}
void ui_event_ControlPanel(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_TOP) {
        lv_indev_wait_release(lv_indev_get_act());
        _ui_screen_delete(&ui_ControlPanel);
        backToMainPanel(e);
    }
    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_delete(&ui_ControlPanel);
        backToMainPanel(e);
    }
    if(event_code == LV_EVENT_SCREEN_LOADED) {
        initcontrolpanel_time_counter(e);
    }
}
void ui_event_Button1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_PRESSED) {
        _ui_screen_change(&ui_lightPanel, LV_SCR_LOAD_ANIM_FADE_ON, 300, 0, &ui_lightPanel_screen_init);
    }
}
void ui_event_Button2(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_PRESSED) {
        _ui_screen_change(&ui_configPanel, LV_SCR_LOAD_ANIM_OVER_LEFT, 300, 0, &ui_configPanel_screen_init);
    }
}
void ui_event_Button3(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_PRESSED) {
        _ui_screen_change(&ui_calendarPanel, LV_SCR_LOAD_ANIM_OVER_LEFT, 300, 0, &ui_calendarPanel_screen_init);
    }
}
void ui_event_Button4(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_PRESSED) {
        _ui_screen_change(&ui_ShutDown, LV_SCR_LOAD_ANIM_OVER_LEFT, 300, 0, &ui_ShutDown_screen_init);
    }
}
void ui_event_Slider1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_VALUE_CHANGED) {
        ScreenLightChange(e);
    }
}
void ui_event_lightPanel(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_TOP) {
        lv_indev_wait_release(lv_indev_get_act());
        ShouDian_light_More(e);
    }
    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_BOTTOM) {
        lv_indev_wait_release(lv_indev_get_act());
        ShouDian_light_Less(e);
    }
    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_RIGHT) {
        lv_indev_wait_release(lv_indev_get_act());
        _ui_screen_delete(&ui_lightPanel);
        _ui_screen_change(&ui_ControlPanel, LV_SCR_LOAD_ANIM_FADE_ON, 300, 0, &ui_ControlPanel_screen_init);
        leaveLightPanel(e);
    }
    if(event_code == LV_EVENT_SCREEN_LOAD_START) {
        startShouDianTong(e);
    }
}
void ui_event_configPanel(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_RIGHT) {
        lv_indev_wait_release(lv_indev_get_act());
        _ui_screen_change(&ui_ControlPanel, LV_SCR_LOAD_ANIM_FADE_ON, 300, 0, &ui_ControlPanel_screen_init);
        _ui_screen_delete(&ui_configPanel);
    }
}
void ui_event_Container5(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_RIGHT) {
        lv_indev_wait_release(lv_indev_get_act());
        _ui_screen_change(&ui_ControlPanel, LV_SCR_LOAD_ANIM_FADE_ON, 300, 0, &ui_ControlPanel_screen_init);
        _ui_screen_delete(&ui_configPanel);
    }
}
void ui_event_Dropdown3(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_VALUE_CHANGED) {
        changeMainPanelChoose(e);
    }
}
void ui_event_Dropdown1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_VALUE_CHANGED) {
        changeScreenOffTime(e);
    }
}
void ui_event_Container4(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_RIGHT) {
        lv_indev_wait_release(lv_indev_get_act());
        _ui_screen_change(&ui_ControlPanel, LV_SCR_LOAD_ANIM_FADE_ON, 300, 0, &ui_ControlPanel_screen_init);
        _ui_screen_delete(&ui_configPanel);
    }
}
void ui_event_Dropdown2(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_VALUE_CHANGED) {
        changeMainPanelChoose(e);
    }
}
void ui_event_Container2(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_SystemAboutPanel, LV_SCR_LOAD_ANIM_FADE_ON, 300, 0, &ui_SystemAboutPanel_screen_init);
    }
    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_RIGHT) {
        lv_indev_wait_release(lv_indev_get_act());
        _ui_screen_change(&ui_ControlPanel, LV_SCR_LOAD_ANIM_FADE_ON, 300, 0, &ui_ControlPanel_screen_init);
        _ui_screen_delete(&ui_configPanel);
    }
}
void ui_event_SystemAboutPanel(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_delete(&ui_SystemAboutPanel);
        _ui_screen_change(&ui_configPanel, LV_SCR_LOAD_ANIM_FADE_ON, 300, 0, &ui_configPanel_screen_init);
    }
}
void ui_event_ShutDown(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_RIGHT) {
        lv_indev_wait_release(lv_indev_get_act());
        _ui_screen_delete(&ui_ShutDown);
        _ui_screen_change(&ui_ControlPanel, LV_SCR_LOAD_ANIM_FADE_ON, 300, 0, &ui_ControlPanel_screen_init);
    }
}
void ui_event_Button5(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        ShutDownYTW(e);
    }
}
void ui_event_Button6(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_ControlPanel, LV_SCR_LOAD_ANIM_FADE_ON, 300, 0, &ui_ControlPanel_screen_init);
        _ui_screen_delete(&ui_ShutDown);
    }
}
void ui_event_noticePanel(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_BOTTOM) {
        lv_indev_wait_release(lv_indev_get_act());
        _ui_screen_delete(&ui_noticePanel);
        backToMainPanel(e);
    }
    if(event_code == LV_EVENT_CLICKED) {
        backToMainPanel(e);
        _ui_screen_delete(&ui_noticePanel);
    }
}
void ui_event_addRemainsPanel(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_LEFT) {
        lv_indev_wait_release(lv_indev_get_act());
        _ui_screen_change(&ui_remainsPanel, LV_SCR_LOAD_ANIM_FADE_ON, 300, 0, &ui_remainsPanel_screen_init);
    }
}
void ui_event_Button11(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if (target == ui_Button11) {
        if(event_code == LV_EVENT_CLICKED) {
            generateARemain(e);
            _ui_screen_delete(&ui_addRemainsPanel);
            _ui_screen_change(&ui_remainsPanel, LV_SCR_LOAD_ANIM_FADE_ON, 300, 0, &ui_remainsPanel_screen_init);
        }
    }
    if (target == ui_Keyboard1) {
        if (event_code == LV_EVENT_CLICKED) {
            if (lv_keyboard_get_selected_btn(ui_Keyboard1) == 39) {
                generateARemain(e);
                _ui_screen_delete(&ui_addRemainsPanel);
                _ui_screen_change(&ui_remainsPanel, LV_SCR_LOAD_ANIM_FADE_ON, 300, 0, &ui_remainsPanel_screen_init);
            }
        }
    }
}
void ui_event_remainsPanel(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_LEFT) {
        lv_indev_wait_release(lv_indev_get_act());
        backToMainPanel(e);
        _ui_screen_delete(&ui_remainsPanel);
    }
}
void ui_event_Button13(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_addRemainsPanel, LV_SCR_LOAD_ANIM_OVER_RIGHT, 300, 0, &ui_addRemainsPanel_screen_init);
    }
}
void ui_event_calendarPanel(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_RIGHT) {
        lv_indev_wait_release(lv_indev_get_act());
        _ui_screen_change(&ui_ControlPanel, LV_SCR_LOAD_ANIM_FADE_ON, 300, 0, &ui_ControlPanel_screen_init);
        _ui_screen_delete(&ui_calendarPanel);
    }
}
lv_calendar_date_t date;
void ui_event_calendar(lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_current_target(e);
    if (event_code == LV_EVENT_CLICKED) {
        lv_calendar_get_pressed_date(target, &date);
        _ui_screen_change(&ui_SchedulePanel, LV_SCR_LOAD_ANIM_OVER_LEFT, 300, 0, &ui_SchedulePanel_screen_init);
    }
}
void ui_event_SchedulePanel(lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_RIGHT) {
        lv_indev_wait_release(lv_indev_get_act());
        _ui_screen_delete(&ui_SchedulePanel);
        _ui_screen_change(&ui_calendarPanel, LV_SCR_LOAD_ANIM_FADE_ON, 300, 0, &ui_calendarPanel_screen_init);
    }
    if(event_code == LV_EVENT_SCREEN_LOADED) {
        initScheduleLabel(e, date);
    }
}
///////////////////// SCREENS ////////////////////

void ui_init(void)
{
    LV_EVENT_GET_COMP_CHILD = lv_event_register_id();

    lv_disp_t * dispp = lv_disp_get_default();
    lv_theme_t * theme = lv_theme_default_init(dispp, lv_palette_main(LV_PALETTE_BLUE), lv_palette_main(LV_PALETTE_RED),
                                               false, LV_FONT_DEFAULT);
//    lv_theme_t *theme = lv_theme_basic_init(dispp);
//    lv_theme_t *theme = lv_theme_mono_init(dispp, false, LV_FONT_DEFAULT);
    lv_disp_set_theme(dispp, theme);
    ui_MainPanel_screen_init();
    ui_MainPanel2_screen_init();
    ui_ControlPanel_screen_init();
    ui_configPanel_screen_init();
    ui_noticePanel_screen_init();
    ui_addRemainsPanel_screen_init();
    ui_remainsPanel_screen_init();
    ui_SchedulePanel_screen_init();
    ui____initial_actions0 = lv_obj_create(NULL);
    lv_disp_load_scr(ui_MainPanel);
}
