// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.0
// LVGL version: 8.3.11
// Project name: ytw3_0

#ifndef _YTW3_0_UI_H
#define _YTW3_0_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#include "../lvgl/lvgl.h"

#include "ui_helpers.h"
#include "components/ui_comp.h"
#include "components/ui_comp_hook.h"
#include "ui_events.h"

// SCREEN: ui_MainPanel
void ui_MainPanel_screen_init(void);
void ui_event_MainPanel(lv_event_t * e);
extern lv_obj_t * ui_MainPanel;
extern lv_obj_t * ui_Panel3;
extern lv_obj_t * ui_shiShi;
extern lv_obj_t * ui_shiGe;
extern lv_obj_t * ui_fenShi;
extern lv_obj_t * ui_fenGe;
extern lv_obj_t * ui_Label1;
extern lv_obj_t * ui_dianliang1;
extern lv_obj_t * ui_miaoShi;
extern lv_obj_t * ui_miaoGe;
extern lv_obj_t * ui_Label4;
extern lv_obj_t * ui_Label5;
extern lv_obj_t * ui_Label2;
// SCREEN: ui_MainPanel2
void ui_MainPanel2_screen_init(void);
void ui_event_MainPanel2(lv_event_t * e);
extern lv_obj_t * ui_MainPanel2;
extern lv_obj_t * ui_Panel4;
extern lv_obj_t * ui_dianliang2;
extern lv_obj_t * ui_Label19;
extern lv_obj_t * ui_Label21;
extern lv_obj_t * ui_Label20;
extern lv_obj_t * ui_Label22;
extern lv_obj_t * ui_Image10;
extern lv_obj_t * ui_Image8;
extern lv_obj_t * ui_Image11;
extern lv_obj_t * ui_Image12;
extern lv_obj_t * ui_Label23;
extern lv_obj_t * ui_Label24;
extern lv_obj_t * ui_Label25;
extern lv_obj_t * ui_Label26;
extern lv_obj_t * ui_Image13;
extern lv_obj_t * ui_Image14;
extern lv_obj_t * ui_Image15;
extern lv_obj_t * ui_Image16;
extern lv_obj_t * ui_Image17;
extern lv_obj_t * ui_Image18;
extern lv_obj_t * ui_Image19;
extern lv_obj_t * ui_Image20;
extern lv_obj_t * ui_Image21;
extern lv_obj_t * ui_Image22;
extern lv_obj_t * ui_Image23;
extern lv_obj_t * ui_Image24;
extern lv_obj_t * ui_Image25;
extern lv_obj_t * ui_Image26;
extern lv_obj_t * ui_Image27;
extern lv_obj_t * ui_Image28;
extern lv_obj_t * ui_Label35;
extern lv_obj_t * ui_Label36;
extern lv_obj_t * ui_Label37;
extern lv_obj_t * ui_Label38;
extern lv_obj_t * ui_shiZhen;
extern lv_obj_t * ui_fenZhen;
extern lv_obj_t * ui_miaoZhen;
extern lv_obj_t * ui_Image1;
extern lv_obj_t * ui_Label43;
extern lv_obj_t * ui_Label27;
extern lv_obj_t * ui_Label18;
// SCREEN: ui_ControlPanel
void ui_ControlPanel_screen_init(void);
void ui_event_ControlPanel(lv_event_t * e);
extern lv_obj_t * ui_ControlPanel;
extern lv_obj_t * ui_Container14;
extern lv_obj_t * ui_Label41;
extern lv_obj_t * ui_Container13;
void ui_event_Button1(lv_event_t * e);
extern lv_obj_t * ui_Button1;
extern lv_obj_t * ui_Label3;
void ui_event_Button2(lv_event_t * e);
extern lv_obj_t * ui_Button2;
extern lv_obj_t * ui_Label6;
void ui_event_Button3(lv_event_t * e);
extern lv_obj_t * ui_Button3;
extern lv_obj_t * ui_Label9;
void ui_event_Button4(lv_event_t * e);
extern lv_obj_t * ui_Button4;
extern lv_obj_t * ui_Label40;
extern lv_obj_t * ui_Button7;
extern lv_obj_t * ui_Button8;
extern lv_obj_t * ui_Button9;
extern lv_obj_t * ui_Button10;
extern lv_obj_t * ui_Container15;
void ui_event_Slider1(lv_event_t * e);
extern lv_obj_t * ui_Slider1;
// SCREEN: ui_lightPanel
void ui_lightPanel_screen_init(void);
void ui_event_lightPanel(lv_event_t * e);
extern lv_obj_t * ui_lightPanel;
extern lv_obj_t * ui_Panel1;
extern lv_obj_t * ui_Label10;
extern lv_obj_t * ui_Label16;
// SCREEN: ui_configPanel
void ui_configPanel_screen_init(void);
void ui_event_configPanel(lv_event_t * e);
extern lv_obj_t * ui_configPanel;
extern lv_obj_t * ui_Container3;
extern lv_obj_t * ui_Label17;
void ui_event_Container5(lv_event_t * e);
extern lv_obj_t * ui_Container5;
extern lv_obj_t * ui_Label30;
void ui_event_Dropdown3(lv_event_t * e);
extern lv_obj_t * ui_Dropdown3;
extern lv_obj_t * ui_Container1;
extern lv_obj_t * ui_Label11;
void ui_event_Dropdown1(lv_event_t * e);
extern lv_obj_t * ui_Dropdown1;
void ui_event_Container4(lv_event_t * e);
extern lv_obj_t * ui_Container4;
extern lv_obj_t * ui_Label8;
void ui_event_Dropdown2(lv_event_t * e);
extern lv_obj_t * ui_Dropdown2;
void ui_event_Container2(lv_event_t * e);
extern lv_obj_t * ui_Container2;
extern lv_obj_t * ui_Label7;
// SCREEN: ui_SystemAboutPanel
void ui_SystemAboutPanel_screen_init(void);
void ui_event_SystemAboutPanel(lv_event_t * e);
extern lv_obj_t * ui_SystemAboutPanel;
extern lv_obj_t * ui_Label12;
// SCREEN: ui_ShutDown
void ui_ShutDown_screen_init(void);
void ui_event_ShutDown(lv_event_t * e);
extern lv_obj_t * ui_ShutDown;
extern lv_obj_t * ui_Label13;
void ui_event_Button5(lv_event_t * e);
extern lv_obj_t * ui_Button5;
void ui_event_Button6(lv_event_t * e);
extern lv_obj_t * ui_Button6;
extern lv_obj_t * ui_Label14;
extern lv_obj_t * ui_Label15;
// SCREEN: ui_noticePanel
void ui_noticePanel_screen_init(void);
void ui_event_noticePanel(lv_event_t * e);
extern lv_obj_t * ui_noticePanel;
extern lv_obj_t * ui_Container6;
extern lv_obj_t * ui_Label29;
// SCREEN: ui_addRemainsPanel
void ui_addRemainsPanel_screen_init(void);
void ui_event_addRemainsPanel(lv_event_t * e);
extern lv_obj_t * ui_addRemainsPanel;
extern lv_obj_t * ui_Container8;
extern lv_obj_t * ui_TextArea1;
void ui_event_Button11(lv_event_t * e);
extern lv_obj_t * ui_Button11;
extern lv_obj_t * ui_Label32;
extern lv_obj_t * ui_Keyboard1;
// SCREEN: ui_remainsPanel
void ui_remainsPanel_screen_init(void);
void ui_event_remainsPanel(lv_event_t * e);
extern lv_obj_t * ui_remainsPanel;
extern lv_obj_t * ui_Container16;
extern lv_obj_t * ui_Label42;
void ui_event_Button13(lv_event_t * e);
extern lv_obj_t * ui_Button13;
extern lv_obj_t * ui_Label28;
extern lv_obj_t * ui____initial_actions0;
// SCREEN: ui_calenderPanel
void ui_calendarPanel_screen_init(void);
extern lv_obj_t * ui_calendarPanel;
extern lv_obj_t * ui_calendar;
extern lv_obj_t * ui_calendar_header;
void ui_event_calendarPanel(lv_event_t * e);
void ui_event_calendar(lv_event_t * e);
// SCREEN: ui_calenderPanel
void ui_SchedulePanel_screen_init(void);
extern lv_obj_t * ui_SchedulePanel;
extern lv_obj_t * ui_Schedule_label;
extern void ui_event_SchedulePanel(lv_event_t * e);

LV_IMG_DECLARE(ui_img_rectangle_8_png);    // assets/Rectangle 8.png
LV_IMG_DECLARE(ui_img_rectangle_7_png);    // assets/Rectangle 7.png
LV_IMG_DECLARE(ui_img_rectangle_9_png);    // assets/Rectangle 9.png
LV_IMG_DECLARE(ui_img_rectangle_10_png);    // assets/Rectangle 10.png
LV_IMG_DECLARE(ui_img_rectangle_12_png);    // assets/Rectangle 12.png
LV_IMG_DECLARE(ui_img_rectangle_11_png);    // assets/Rectangle 11.png
LV_IMG_DECLARE(ui_img_rectangle_13_png);    // assets/Rectangle 13.png
LV_IMG_DECLARE(ui_img_rectangle_14_png);    // assets/Rectangle 14.png
LV_IMG_DECLARE(ui_img_rectangle_15_png);    // assets/Rectangle 15.png
LV_IMG_DECLARE(ui_img_rectangle_16_png);    // assets/Rectangle 16.png
LV_IMG_DECLARE(ui_img_rectangle_2_png);    // assets/Rectangle 2.png
LV_IMG_DECLARE(ui_img_rectangle_1_png);    // assets/Rectangle 1.png
LV_IMG_DECLARE(ui_img_rectangle_3_png);    // assets/Rectangle 3.png
LV_IMG_DECLARE(ui_img_ellipse_1_png);    // assets/Ellipse 1.png
LV_IMG_DECLARE(ui_img_rectangle_5_png);    // assets/Rectangle 5.png
LV_IMG_DECLARE(ui_img_rectangle_6_png);    // assets/Rectangle 6.png

LV_FONT_DECLARE(ui_font_changfangxing);
LV_FONT_DECLARE(ui_font_guanji48);
LV_FONT_DECLARE(ui_font_jiahao48);
LV_FONT_DECLARE(ui_font_rili48);
LV_FONT_DECLARE(ui_font_shezhi48);
LV_FONT_DECLARE(ui_font_shoudian48);
LV_FONT_DECLARE(ui_font_gouzi48);

void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
