// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.0
// LVGL version: 8.3.11
// Project name: ytw3_0

#ifndef _UI_EVENTS_H
#define _UI_EVENTS_H

#ifdef __cplusplus
extern "C" {
#endif

void leaveMainPanel1(lv_event_t * e);
void init_time_counter(lv_event_t * e);
void changeMainPanel(lv_event_t * e);
void leaveMainPanel2(lv_event_t * e);
void init_time_counter_2(lv_event_t * e);
void backToMainPanel(lv_event_t * e);
void initcontrolpanel_time_counter(lv_event_t * e);
void ScreenLightChange(lv_event_t * e);
void ShouDian_light_More(lv_event_t * e);
void ShouDian_light_Less(lv_event_t * e);
void leaveLightPanel(lv_event_t * e);
void startShouDianTong(lv_event_t * e);
void changeMainPanelChoose(lv_event_t * e);
void changeScreenOffTime(lv_event_t * e);
void ShutDownYTW(lv_event_t * e);
void generateARemain(lv_event_t * e);
void initScheduleLabel(lv_event_t *e, lv_calendar_date_t date);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
