// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.0
// LVGL version: 8.3.11
// Project name: ytw3_0

#include <stdio.h>
#include "ui.h"
#include "LCD_Control.h"
#include "a_heiyt_task_lvgl/change_things.h"
#include "heiyt_task.h"
#include "system.h"

//设置里面，控制显示哪个表盘，0是显示数字表盘，1是显示指针表盘，2是都可显示，通过changeMainPanel函数切换
char xianshi_which_set = 0;
//切换回去应该显示的表盘,0表示显示数字表盘，1表示显示指针表盘
char xianshi_which = 0;

uint16_t ShouDianTong_light = 90;
char sdt_light_show[3];

extern osTimerId_t sleep_timerHandle;
//两个主界面的功能
void init_time_counter(lv_event_t *e) {
    lv_Timer_1 = lv_timer_create(refresh_time, 200, NULL);
    refresh_time_BLE();
    lv_timer_pause(lv_Timer_2);
}
void changeMainPanel(lv_event_t * e){
    // Your code here
    if (xianshi_which_set == 2) {
        if (xianshi_which == 0) {
            //切换到指针表盘
            _ui_screen_change(&ui_MainPanel2, LV_SCR_LOAD_ANIM_FADE_ON, 300, 0, &ui_MainPanel2_screen_init);
            _ui_screen_delete(&ui_MainPanel);
            xianshi_which = 1;
        } else if (xianshi_which == 1) {
            //切换到数字表盘
            _ui_screen_change(&ui_MainPanel, LV_SCR_LOAD_ANIM_FADE_ON, 300, 0, &ui_MainPanel_screen_init);
            _ui_screen_delete(&ui_MainPanel2);
            xianshi_which = 0;
        }
    }
}
void init_time_counter_2(lv_event_t * e) {
    // Your code here
    lv_Timer_2 = lv_timer_create(refresh_time_2, 200, NULL);
    refresh_time_BLE_2();
    lv_timer_pause(lv_Timer_1);
}
void backToMainPanel(lv_event_t * e) {
    // Your code here
    if (xianshi_which_set == 2) {
        if (xianshi_which == 0) {
            //切换到数字表盘
            _ui_screen_change(&ui_MainPanel, LV_SCR_LOAD_ANIM_FADE_ON, 300, 0, &ui_MainPanel_screen_init);
        }
        if (xianshi_which == 1) {
            //切换到指针表盘
            _ui_screen_change(&ui_MainPanel2, LV_SCR_LOAD_ANIM_FADE_ON, 300, 0, &ui_MainPanel2_screen_init);
        }
    }
    if (xianshi_which_set == 0) {
        _ui_screen_change(&ui_MainPanel, LV_SCR_LOAD_ANIM_FADE_ON, 300, 0, &ui_MainPanel_screen_init);
        _ui_screen_delete(&ui_MainPanel2);
    }
    if (xianshi_which_set == 1) {
        _ui_screen_change(&ui_MainPanel2, LV_SCR_LOAD_ANIM_FADE_ON, 300, 0, &ui_MainPanel2_screen_init);
        _ui_screen_delete(&ui_MainPanel);
    }
    if (!(lv_Timer_3->paused)) {
        lv_timer_pause(lv_Timer_3);
    }
}
void initcontrolpanel_time_counter(lv_event_t * e){
    if (lv_Timer_3->paused) {
        lv_timer_resume(lv_Timer_3);
    }
}
void leaveMainPanel1(lv_event_t * e){
    xianshi_which = 0;
}
void leaveMainPanel2(lv_event_t * e){
    xianshi_which = 1;
}

//手电筒界面的功能
void ShouDian_light_More(lv_event_t * e)
{
    // Your code here
    if (ShouDianTong_light < 290) {
        ShouDianTong_light += 30;
    }
    LCD_BLK_Set(ShouDianTong_light);
    sprintf(sdt_light_show, "%d", ShouDianTong_light);
    lv_label_set_text(ui_Label10, sdt_light_show);
}
void ShouDian_light_Less(lv_event_t * e)
{
    if (ShouDianTong_light > 50) {
        ShouDianTong_light -= 30;
    }
    LCD_BLK_Set(ShouDianTong_light);
    sprintf(sdt_light_show, "%d", ShouDianTong_light);
    lv_label_set_text(ui_Label10, sdt_light_show);
}
void leaveLightPanel(lv_event_t * e){
    LCD_BLK_Set(light);
}
void ScreenLightChange(lv_event_t * e)
{
    // Your code here
    light = lv_slider_get_value(ui_Slider1);
    LCD_BLK_Set(light);
}
void startShouDianTong(lv_event_t * e)
{
    int i = lv_dropdown_get_selected(ui_Dropdown3);
    switch (i) {
        case 0: i = 90;break;
        case 1: i = 120;break;
        case 2: i = 150;break;
        case 3: i = 180;break;
        case 4: i = 240;break;
        case 5: i = 300;break;
    }
    ShouDianTong_light = i;
    LCD_BLK_Set(ShouDianTong_light);
    sprintf(sdt_light_show, "%d", ShouDianTong_light);
    lv_label_set_text(ui_Label10, sdt_light_show);
}

//设置界面的功能
void changeScreenOffTime(lv_event_t * e){
    int i;
    i = lv_dropdown_get_selected(ui_Dropdown1);
    switch (i) {
        case 0: sleepTime = 10000; osTimerStart(sleep_timerHandle, pdMS_TO_TICKS(sleepTime)); break;
        case 1: sleepTime = 15000; osTimerStart(sleep_timerHandle, pdMS_TO_TICKS(sleepTime)); break;
        case 2: sleepTime = 20000; osTimerStart(sleep_timerHandle, pdMS_TO_TICKS(sleepTime)); break;
        case 3: sleepTime = 30000; osTimerStart(sleep_timerHandle, pdMS_TO_TICKS(sleepTime)); break;
        case 4: sleepTime = 60000; osTimerStart(sleep_timerHandle, pdMS_TO_TICKS(sleepTime)); break;
        case 5: sleepTime = 300000; osTimerStart(sleep_timerHandle, pdMS_TO_TICKS(sleepTime)); break;
        case 6: sleepTime = 600000; osTimerStart(sleep_timerHandle, pdMS_TO_TICKS(sleepTime)); break;
        case 7: sleepTime = 0xffffffff; break;
    }
}
void changeMainPanelChoose(lv_event_t * e) {
    //选择是显示数字表盘还是指针表盘
    xianshi_which_set = lv_dropdown_get_selected(ui_Dropdown2);
}

//关机界面的功能
void ShutDownYTW(lv_event_t * e){
    YTW_System_Close();
}

//待办界面的功能
void ui_event_Checkbox(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    lv_obj_t *target_parent = lv_obj_get_parent(target);
    if(event_code == LV_EVENT_LONG_PRESSED) {
        lv_obj_del(target);
        lv_obj_del(target_parent);
    }
}
void generateARemain(lv_event_t * e)
{
    lv_obj_t * ui_container , * ui_checkbox;
    const char *remain_txt = lv_textarea_get_text(ui_TextArea1);
    if (strlen(remain_txt) == 0) {
        return;
    }
    ui_container = lv_obj_create(ui_remainsPanel);
    lv_obj_remove_style_all(ui_container);
    lv_obj_set_width(ui_container, 280);
    lv_obj_set_height(ui_container, 50);
    lv_obj_set_x(ui_container, 0);
    lv_obj_set_y(ui_container, 0);
    lv_obj_set_align(ui_container, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_container, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_checkbox = lv_checkbox_create(ui_container);
    lv_checkbox_set_text(ui_checkbox, remain_txt);
    lv_obj_set_width(ui_checkbox, LV_SIZE_CONTENT);
    lv_obj_set_height(ui_checkbox, LV_SIZE_CONTENT);
    lv_obj_align(ui_checkbox, LV_ALIGN_LEFT_MID, 20, 0);
    lv_obj_add_flag(ui_checkbox, LV_OBJ_FLAG_SCROLL_ON_FOCUS);
    lv_obj_set_style_text_font(ui_checkbox, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_textarea_set_text(ui_TextArea1,"");
    lv_obj_add_event_cb(ui_checkbox, ui_event_Checkbox, LV_EVENT_ALL, NULL);
}

void ui_event_ScheduleLabel(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    lv_obj_t *target_parent = lv_obj_get_parent(target);
    if(event_code == LV_EVENT_LONG_PRESSED) {
        lv_obj_del(target);
        lv_obj_del(target_parent);
    }
}
void initScheduleLabel(lv_event_t * e,lv_calendar_date_t date)
{
    //读取数据库里面的日程,看有几条
    int n = 6;//假设这一天有6条
    for (int i = 0; i < n; i++) {
        lv_obj_t * ui_container , * ui_schedule_label;

        ui_container = lv_obj_create(ui_SchedulePanel);
        lv_obj_remove_style_all(ui_container);
        lv_obj_set_width(ui_container, 280);
        lv_obj_set_height(ui_container, 50);
        lv_obj_set_x(ui_container, 0);
        lv_obj_set_y(ui_container, 0);
        lv_obj_set_align(ui_container, LV_ALIGN_CENTER);
        lv_obj_clear_flag(ui_container, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

        ui_schedule_label = lv_label_create(ui_container);
        if (i == 0) {
            lv_label_set_text_fmt(ui_schedule_label, "%d.%d.%d", date.year, date.month, date.day);
        } else {
            lv_label_set_text(ui_schedule_label, "xx");
        }
        lv_obj_set_width(ui_schedule_label, LV_SIZE_CONTENT);
        lv_obj_set_height(ui_schedule_label, LV_SIZE_CONTENT);
        lv_obj_align(ui_schedule_label, LV_ALIGN_LEFT_MID, 20, 0);
        lv_obj_add_flag(ui_schedule_label, LV_OBJ_FLAG_CLICKABLE);
        lv_obj_set_style_text_font(ui_schedule_label, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);

        lv_obj_add_event_cb(ui_schedule_label, ui_event_ScheduleLabel, LV_EVENT_ALL, NULL);
    }
}